spring:
  application:
    name: usermanagesystem
  datasource:
    url: jdbc:mysql://localhost:3306/usermanage_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
  thymeleaf:
    cache: false
    enabled: true
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/,classpath:/resources/

  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  messages:
    encoding: UTF-8



