spring:
  application:
    name: usermanagesystem
  datasource:
    url: jdbc:mysql://localhost:3306/usermanager_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
  thymeleaf:
    cache: false
    enabled: true
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/,classpath:/resources/

  main:
    allow-bean-definition-overriding: true
  devtools:
    livereload:
      enabled: true
      port: 35729
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
  messages:
    basename: i18n.messages
    encoding: utf-8




